wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30000_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30000_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30000_irnt.gwas.imputed_v3.female.tsv.bgz -O 30000_irnt.gwas.imputed_v3.female.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30000_irnt.gwas.imputed_v3.male.tsv.bgz -O 30000_irnt.gwas.imputed_v3.male.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30000_raw.gwas.imputed_v3.both_sexes.tsv.bgz -O 30000_raw.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30000_raw.gwas.imputed_v3.female.tsv.bgz -O 30000_raw.gwas.imputed_v3.female.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30000_raw.gwas.imputed_v3.male.tsv.bgz -O 30000_raw.gwas.imputed_v3.male.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30010_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30010_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30010_irnt.gwas.imputed_v3.female.tsv.bgz -O 30010_irnt.gwas.imputed_v3.female.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30010_irnt.gwas.imputed_v3.male.tsv.bgz -O 30010_irnt.gwas.imputed_v3.male.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30010_raw.gwas.imputed_v3.both_sexes.tsv.bgz -O 30010_raw.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30010_raw.gwas.imputed_v3.female.tsv.bgz -O 30010_raw.gwas.imputed_v3.female.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30010_raw.gwas.imputed_v3.male.tsv.bgz -O 30010_raw.gwas.imputed_v3.male.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30020_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30020_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30020_irnt.gwas.imputed_v3.female.tsv.bgz -O 30020_irnt.gwas.imputed_v3.female.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30020_irnt.gwas.imputed_v3.male.tsv.bgz -O 30020_irnt.gwas.imputed_v3.male.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30020_raw.gwas.imputed_v3.both_sexes.tsv.bgz -O 30020_raw.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30020_raw.gwas.imputed_v3.female.tsv.bgz -O 30020_raw.gwas.imputed_v3.female.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30020_raw.gwas.imputed_v3.male.tsv.bgz -O 30020_raw.gwas.imputed_v3.male.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30030_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30030_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30030_irnt.gwas.imputed_v3.female.tsv.bgz -O 30030_irnt.gwas.imputed_v3.female.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30030_irnt.gwas.imputed_v3.male.tsv.bgz -O 30030_irnt.gwas.imputed_v3.male.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30030_raw.gwas.imputed_v3.both_sexes.tsv.bgz -O 30030_raw.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30030_raw.gwas.imputed_v3.female.tsv.bgz -O 30030_raw.gwas.imputed_v3.female.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30030_raw.gwas.imputed_v3.male.tsv.bgz -O 30030_raw.gwas.imputed_v3.male.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30040_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30040_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30040_irnt.gwas.imputed_v3.female.tsv.bgz -O 30040_irnt.gwas.imputed_v3.female.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30040_irnt.gwas.imputed_v3.male.tsv.bgz -O 30040_irnt.gwas.imputed_v3.male.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30040_raw.gwas.imputed_v3.both_sexes.tsv.bgz -O 30040_raw.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30040_raw.gwas.imputed_v3.female.tsv.bgz -O 30040_raw.gwas.imputed_v3.female.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30040_raw.gwas.imputed_v3.male.tsv.bgz -O 30040_raw.gwas.imputed_v3.male.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30080_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30080_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30080_irnt.gwas.imputed_v3.female.tsv.bgz -O 30080_irnt.gwas.imputed_v3.female.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30080_irnt.gwas.imputed_v3.male.tsv.bgz -O 30080_irnt.gwas.imputed_v3.male.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30080_raw.gwas.imputed_v3.both_sexes.tsv.bgz -O 30080_raw.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30080_raw.gwas.imputed_v3.female.tsv.bgz -O 30080_raw.gwas.imputed_v3.female.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30080_raw.gwas.imputed_v3.male.tsv.bgz -O 30080_raw.gwas.imputed_v3.male.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30090_irnt.gwas.imputed_v3.both_sexes.tsv.bgz -O 30090_irnt.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30090_irnt.gwas.imputed_v3.female.tsv.bgz -O 30090_irnt.gwas.imputed_v3.female.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30090_irnt.gwas.imputed_v3.male.tsv.bgz -O 30090_irnt.gwas.imputed_v3.male.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30090_raw.gwas.imputed_v3.both_sexes.tsv.bgz -O 30090_raw.gwas.imputed_v3.both_sexes.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30090_raw.gwas.imputed_v3.female.tsv.bgz -O 30090_raw.gwas.imputed_v3.female.tsv.bgz
wget https://broad-ukb-sumstats-us-east-1.s3.amazonaws.com/round2/additive-tsvs/30090_raw.gwas.imputed_v3.male.tsv.bgz -O 30090_raw.gwas.imputed_v3.male.tsv.bgz
